### ISSUE TITLE
When retargeting sandbox to a new revision, it hard codes the project source file name to be 'project.pj' rather than the *.pj file used for input

### ISSUE THREAD

**Issue by JoeM1** [XenuIsWatching/mks_checkpoints_to_git#1]
D:\Repositories_Git\LIPS>d:\Python27\python d:\Python27\PTC2Git\mks_checkpoints_to_git.py d:\MKS_projects\P18000\LifecycleInstallProps\LIPS.pj | git fast-import
Connecting to s306a57:7001 ...
Connecting to s306a57:7001 as 8xxxx0 ...
Connecting to s306a57:7001 ...
Connecting to s306a57:7001 as 8xxxx0 ...
Connecting to s306a57:7001 ...
Connecting to s306a57:7001 as 8xxxx0 ...
Creating build sandbox...
_**D:\Repositories_Git\LIPS\tmp\LIPS.pj**_
Resynchronizing files...
Connecting to s306a57:7001 ...
Connecting to s306a57:7001 as 8xxxx0 ...
_**D:\Repositories_Git\LIPS\tmp/project.pj**_
Failed to retarget sandbox D:\Repositories_Git\LIPS\tmp/project.pj: Retarget failed: The specified sandbox is not registered
as a top level sandbox

**Comment by XenuIsWatching** [comment]
You have to specify the project.pj file that resides within the PTC integrity server and LIPS.pj. ex.
python mks_checkpoints_to_git.py <MKS_project_path**/project.pj**> | git fast-import

_but...._ it looks like you have renamed this project.pj file which I didn't know was possible. Try modifying line 76 in the python code to say LIPS.pj instead of project.pj.

Anyways, I haven't used integrity in a year and I not longer have access to a server to do any debugging anymore.

**Comment by JoeM1** [comment]
Ryan,

Changing “/project.pj” to “\LIPS.pj” allowed the job to run to what appears to be a good eoj.  Thank you…!

I’m not well versed in Git however; what is needed to be done to ‘create’ the Git repository………..or did the job do that and I don’t know where to look…?   ☺

Thanks in advance for your input…!

___________________________
JOE  MRAZ  -   Integrity  Admin
                     [cid:image001.png@01D0C2E8.473E2280]
                IT  Specialist
  Social Security Administration
     DCS/OSE/OSA/DESEI/CEB
            410/965-5136
- - - - - - - - - - - - - - - - - - - - - - - - -
   (Now this is  P E A C E  –  John  14 : 27)

TELEWORK  – Tuesdays/Fridays

**Comment by XenuIsWatching** [comment]
If you follow the readme.md I wrote, you'll need to enter `git init` into the git command line.

**Comment by JoeM1** [comment]
I ran the git init at the beginning as directed, in the d:\Repositories_Git\LIPS directory and it said it worked; but I see nothing ‘git-ish’ there….

___________________________
JOE  MRAZ  -   Integrity  Admin
                     [cid:image001.png@01D0C2E8.473E2280]
                IT  Specialist
  Social Security Administration
     DCS/OSE/OSA/DESEI/CEB
            410/965-5136
- - - - - - - - - - - - - - - - - - - - - - - - -
   (Now this is  P E A C E  –  John  14 : 27)

TELEWORK  – Tuesdays/Fridays

**Comment by XenuIsWatching** [comment]
it's a hidden folder. should be named ```.git```
You'll probably need to checkout a branch as well after running the script to get a working copy

**Comment by JoeM1** [comment]
Got it…!  Thanks again Ryan;  I’ll pursue some folks locally now that it appears I’ve gotten some files.  I really appreciated your patient assistance…!

Have a great weekend…!!

___________________________
JOE  MRAZ  -   Integrity  Admin
                     [cid:image001.png@01D0C2E8.473E2280]
                IT  Specialist
  Social Security Administration
     DCS/OSE/OSA/DESEI/CEB
            410/965-5136
- - - - - - - - - - - - - - - - - - - - - - - - -
   (Now this is  P E A C E  –  John  14 : 27)

TELEWORK  – Tuesdays/Fridays

**Comment by XenuIsWatching** [comment]
@JoeM1 I pushed a fix for this a while back. Since I don't have access to a server anymore. Could you let me know if this new commit works for you without any modifications.
