### ISSUE TITLE
Branch name doesn't conform to GIT standards

### ISSUE THREAD

**Issue by shivam3108** [XenuIsWatching/mks_checkpoints_to_git#4]
Hi 

We are using this script to migrate source code from PTC integrity to git using python 3.7.
Getting below mention error.
error: fatal Branch name doesn't conform to GIT standards: refs/heads/master

We are getting this error for command **script: print('commit refs/heads/master')** given in the script.

we assume that print function is adding \r\n @ the end of the branch name. So, tried below mentioned solutions for the same:
1. Tried adding end='' in the print command
2. Logging info
3. sys.stdout.write in place of print function
4. updated the script to:
if platform.system() == 'Windows':
    import msvcrt, os
    msvcrt.setmode(sys.stdout.fileno(), os.O_BINARY)

Kindly help in this issue!!!!!!!!!!!!!!!

**Comment by XenuIsWatching** [comment]
Sorry, but I can no longer maintain or test this script due to no longer having access to a PTC integrity server. You're welcome to take a look at the people who have forked this repo.
